[package]
name = "museum-arii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.24.0", features = ["sync"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"